name: inception

services:
  nginx:
    #use Dockerfile instead of building the container inside compose
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile

    volumes:
      - test_volume:/var/www/test

    #Map the host port 443 to the container port 443 --> HTTPS
    ports:
        - 8003:8003

volumes:
  test_volume:
    #volume will be managed locally on the host
    driver: local
    driver_opts:
      type: 'none'
      #directly map the host to the container
      o: 'bind'
      #specify the path on the host that will be mounted to the volume
      device: '/Users/lemonb/Documents/Sonstiges/test'

    
